basic:
    name: 'https://www.kj.com'
    environments:
        production: 'https://www.kj.com'
        staging: ''
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 640
        - 1024
        - 1240
    pages:
        - '/shop-wines-featured-wine-sets/?prefn1=showInSearch&prefv1=webOnly%7Cboth&srule=product-name-ascending&start=0&sz=7'
        - '/shop-wines-featured-merchandise/?prefn1=showInSearch&prefv1=webOnly%7Cboth&srule=product-name-ascending&start=0&sz=1'
        - '/shop-wines/?prefn1=showInSearch&prefv1=webOnly%7Cboth&srule=product-name-ascending&start=0&sz=24'
        - '/shop-wines-vintners-reserve/?prefn1=showInSearch&prefv1=webOnly%7Cboth&srule=product-name-ascending&start=0&sz=12'
        - '/shop-wines-by-collection-grand-reserve/?prefn1=showInSearch&prefv1=webOnly%7Cboth&srule=product-name-ascending&start=0&sz=5'
        - '/shop-wines-jackson-estate/?prefn1=showInSearch&prefv1=webOnly%7Cboth&srule=product-name-ascending&start=0&sz=24'
        - '/shop-wines-stature/?prefn1=showInSearch&prefv1=webOnly%7Cboth&srule=product-name-ascending&start=0&sz=5'
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: '#modal-agegate, .osano-cm-window__dialog, .modal-backdrop.show, .plp-back-to-top_content, #legalNotification, section.im-header, aside.spb.spb--sitePromotionalBannerLocation-belowheader.spb--sitePromotionalBannerID-kj-promotional-banner.js-height-promotionbanner.spb--loaded, .jfw-plp-storepage__above-product-grid-wrapper, .jfw-plp-storepage__below-product-grid, footer#footercontent, div#userwayAccessibilityIcon'
    delay: 15
    scroll: true
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
